feat: add Grenache gris as an option,
Vinebase/wine-knowledge pull request #4
Opened 2022-08-09 12:22 UTC by RolandStuder

fixes https://github.com/Vinebase/vinebase/issues/5265

2022-08-09 12:23 UTC, RolandStuder commented
@kieranklaassen no idea if I understood that right: https://github.com/Vinebase/vinebase/issues/5265

2022-08-09 18:03 UTC, kieranklaassen commented
This is a category, you should use the https://github.com/Vinebase/wine-knowledge/blob/main/Categorization/grape_types_taxonomy.csv

2022-08-09 18:04 UTC, kieranklaassen requested changes
Please add grape type in this file: https://github.com/Vinebase/wine-knowledge/blob/main/Categorization/grape_types_taxonomy.csv

Styles are something different.

2022-08-10 13:40 UTC, kieranklaassen approved these changes

2022-08-10 13:40 UTC, merged